---
linters:
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - exhaustive
    - gochecknoinits
    - gocognit
    - gocritic
    - gocyclo
    - goerr113
    - gofumpt
    - goimports
    - gomnd
    - goprintffuncname
    - govet
    - misspell
    - nakedret
    - nestif
    - nlreturn
    - noctx
    - tparallel
    - typecheck
    - unparam
    - wrapcheck
    - wsl
